### ISSUE TITLE
Suggestion: document list of fields included in each pre-computed dump

### ISSUE THREAD

**Issue by sheluchin** [phronmophobic/dewey#2]
Hi @phronmophobic,

Thank you for maintaining dewey. I'm trying to incorporate some of the provided data and retrieval pathways into my projects. Would you consider updating the docs to include the fields and their meanings included in each pre-computed dump? I think this would help make dewey more approachable and would remove the need to run the project and call `com.phronemophobic.dewey.util/read-edn` to see what's inside.

**Comment by phronmophobic** [comment]
> Would you consider updating the docs to include the fields and their meanings included in each pre-computed dump?

Yea, I can give that a shot. I'll try to do that in the next week or so.

> I think this would help make dewey more approachable and would remove the need to run the project and call com.phronemophobic.dewey.util/read-edn to see what's inside.

As an aside, `zless` is great for peeking inside of compressed files at the command line.

**Comment by phronmophobic** [comment]
@sheluchin ok, just added a few more docs. I realize the docs are still pretty sparse, but most of the data comes directly from github and they don't really document their data.

**Comment by sheluchin** [comment]
Thank you, @phronmophobic. That is pretty helpful, especially the reference for `:lib`.

>As an aside, zless/less is great for peeking inside of compressed files at the command line.

I didn't know about `zless`. Thanks again!


Closing this as resolved as I think it addresses as much as possible given the available information.
