### ISSUE TITLE
Reproducibility: include `:git/sha` or similar in `analysis.edn`

### ISSUE THREAD

**Issue by sheluchin** [phronmophobic/dewey#7]
Hi @phronmophobic,

You've mentioned that some of the effort you are expanding on Dewey right now is around the repeatability of the analysis process. I'd like to suggest that when a Clojure repo is analyzed, the resulting analysis data should include the repo's commit hash on which the analysis was performed. I think the benefits of this one additional piece of data are fairly clear, but I could expand on my rationale if the use case is not evident. Do you have any thoughts on this idea?

**Comment by phronmophobic** [comment]
I totally agree. The next release will include commit shas.

**Comment by sheluchin** [comment]
I see it in the README now as well. Thanks, @phronmophobic!

https://github.com/phronmophobic/dewey/blob/6c829589d05ba1da8e86f882e64a7eaccb6eb112/README.md?plain=1#L43-L50
