### ISSUE TITLE
why "FiraCode" ?

### ISSUE THREAD

**Issue by behrica** [phronmophobic/dewey#9]
Why is thgis in the list ?

It has no Clojure related keyword :
https://github.com/tonsky/FiraCode

**Comment by phronmophobic** [comment]
The method for finding clojure libraries is summarized at https://github.com/phronmophobic/dewey#1-find-all-clojure-libraries.

Basically, FiraCode is categorized by github's search as a clojure library, https://github.com/search?l=Clojure&q=Firacode&type=Repositories

**Comment by phronmophobic** [comment]
@behrica , Does that answer your question?
